apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/profile-controller/config/overlays/kubeflow?ref=cce5c88047815c45df8a52c8592e5890ae1b1949 # tag=v1.7.0

patchesStrategicMerge:
  - patch-admin.yaml

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newName: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newTag: v1.3.0-rc.1
- name: public.ecr.aws/j1r0q0g6/notebooks/profile-controller
  newName: public.ecr.aws/j1r0q0g6/notebooks/profile-controller
  newTag: v1.3.0-rc.1
