apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/notebook-controller/config/overlays/kubeflow?ref=cce5c88047815c45df8a52c8592e5890ae1b1949 # tag=v1.7.0

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newName: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newTag: v1.3.0-rc.1
